version: '3.8'


services:
  web:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  
  db:
    # container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    image: postgres:12.0-alpine
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: