version: '3.8'


services:
  web:
    # container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      # - 8000:8000
      - 8000
    env_file:
      - .env.dev
    depends_on:
      - db
  
  db:
    # container_name: postgres
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_USER=augustine"
      - "POSTGRES_PASSWORD=fitpet123@@"
      - "POSTGRES_DB=django_db"

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data: