version: '3.8'


services:
  web:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000